#!/usr/bin/env php
<?php
/**
 * if we're running from phar load the phar autoload,
 * else let the script 'robo' search for the autoloader
 */
$vendor = '';
if (strpos(basename(__FILE__), 'phar')) {
    $vendor = 'phar://tg.phar/vendor';
} else {
    //TODO - will this fail if we run tg from a dir that matches this pattern?
    if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
        $vendor = __DIR__ . '/../vendor';
    } else {
        $vendor = 'phar://tg.phar/vendor';
    }
}
require_once $vendor . '/autoload.php';
$runner = new \twhiston\tg\Tg($vendor);
$exitCode = $runner->run();
exit($exitCode);
