#!/usr/bin/env php
<?php
/**
 * if we're running from phar load the phar autoload,
 * else let the script 'robo' search for the autoloader
 */
$vendor = '';
if (strpos(basename(__FILE__), 'phar')) {
    $vendor = 'phar://tx.phar/vendor';
    require_once $vendor . '/autoload.php';
} else {
    if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
        $vendor = __DIR__ . '/../vendor';
        require_once $vendor . '/autoload.php';
    } else {
        $vendor = 'phar://tx.phar/vendor';
        require_once $vendor . '/autoload.php';
    }
}
$runner = new \twhiston\tx\Tx($vendor);
$exitCode = $runner->run();
exit($exitCode);